server:
  port: 9090
spring:
  datasource:
    url: jdbc:mysql:///email
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
dubbo:
  application:
    name: emaile_service
  registry:
    address: zookeeper://192.168.204.128:2181
  protocol:
    port: -1